### ISSUE TITLE
[discussion] future directions

### ISSUE THREAD

**Issue by jschilli** [sir-dunxalot/ember-cli-concat#10]
@sir-dunxalot I've been sketching out a list of options that would meet our use cases (large ember app migrating to ember-cli from broc build from rackup) 

- enabled: true
- forceConcatenation: false
- outputFilename: app
- *scripts*ContentFor
- *styles*ContentFor

etc

these all exist.

there is a PR out to preserve originals

and additionally I'd now like to `enableScripts` and/or `enableStyles` 

The specific case for handling styles differently is our support for themes - which can be large and should never be concatenated.  Currently I have to choose between concatenation and leveraging the standard ember-cli build model.

So it strikes me that in the spirit of broccoli and ember-cli itself where lots of smaller modules are combined to create greatness whether the best move here is to create `ember-cli-concat-scripts` and `ember-cli-concat-styles`

The options become symmetrical and the code becomes cleaner by only focusing on one concern.

Food for thought.

Thoughts?

**Comment by sir-dunxalot** [comment]
Some really good thoughts here. I'll respond in more detail in the morning but I wanted to let you know I've read it through a couple of times and am thinking about everything mentioned. Again, sorry for the delay.

**Comment by sir-dunxalot** [comment]
Hi Jeff - I haven't forgotten about this sorry for the delay. I'm going to set a milestone to get all of this pushed through by the end of next week.

**Comment by sir-dunxalot** [comment]
I have done work to separate out the concerns of the style and script tags. Since a lot of the code is shared I don't think it's beneficial (yet) to seperate into two different addons. Part of the change also updates how the outputPaths object is parsed (for more compatibility with future Ember CLI releases).I'll have a PR up for review soon.

**Comment by sir-dunxalot** [comment]
@jschilli Given your planning for the different options and some of the open issues I have made a first attempt at combining it all into v1 in this [PR](https://github.com/sir-dunxalot/ember-cli-concat/pull/15). Please let me know what you think.

Noticeable changes are:

- Internal changes to be more flexible regarding the object pattern app `outputPaths` are stored in. For example, `app`, `vendor`, and `testSupport` can all be strings or objects.
- Some existing options have been separated into `js` and `css` objects:

```js
  js: {
    concat: false, // Added
    contentFor: 'body-footer',
    footer: null,
    header: null,
    preserveOriginal: false
  },

  css: {
    concat: true, // Added
    contentFor: 'head-footer',
    footer: null,
    header: null,
    preserveOriginal: false
  },
```

- Concatenation is no longer assumed in production. However, all of the above options can be set in the Brocfile as follows:

```
var EmberAddon = require('ember-cli/lib/broccoli/ember-addon');
var environment = process.env.EMBER_ENV;

var options = {
  storeConfigInMeta: false,
  fingerprint: {
    enabled: true,
  },
  emberCliConcat: {
    /* Test custom options here */
  }
};

if (environment === 'development') {
  emberCliConcat.js.concat = false;
  emberCliConcat.css.concat = false;
}

var app = new EmberAddon(options);

module.exports = app.toTree();
```

**Comment by sir-dunxalot** [comment]
Additionally, concat will include `test-support` files whether concatenating scripts or not. A typical `tests/dummy/app/index.html` file will looks like:`

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dummy Tests</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{content-for 'head'}}
    {{content-for 'test-head'}}

    {{content-for 'head-footer'}}
    {{content-for 'test-head-footer'}}
  </head>
  <body>

    {{content-for 'body'}}
    {{content-for 'test-body'}}

    {{content-for 'body-footer'}}

    <script src="testem.js"></script>
    <script src="assets/test-loader.js"></script>

    {{content-for 'test-body-footer'}}
  </body>
</html>
```

**Comment by sir-dunxalot** [comment]
So I've been going back and forth on this since #15 and I haven't been able to come up with a reliable way to ensure the correct assets are concatenated at the `/tests` route. The problem there is the environment is equal to `'development'`. My best path forward is probably to leave the `tests/app/index.html` file as is (i.e. leave the asset paths in there) and make sure original files are always left in for development, or at least have that as the default.

**Comment by sir-dunxalot** [comment]
@jschilli  #15 Has merged v1.0.0 into master. It's a massive improvement on what we had before - a mush better foundation for making this addon even better moving forward. Please open issues for any outstanding problems you forsee. The one issue I had was testing - I couldn't get the Mocha Chai implementation setup.

**Comment by jschilli** [comment]
Thx. Will review.  I appreciate the effort. 

-jeff

**Comment by sir-dunxalot** [comment]
My pleasure. My team will be using this in production moving forward so I should be able to keep a much better handle on it.
