### ISSUE TITLE
HTML Entities

### ISSUE THREAD

**Issue by dallasread** [sir-dunxalot/ember-cli-concat#11]
Thanks for the great addon!

In a few of my handlebars templates, I use \&times; (&times;) and \&rarr; (&rarr;).

Everything works peachy in development.

When I build for production, my final concatenated script has replaced them with their actual entities. For example:

var r=e.createTextNode("×");

... which shows up as a Ã— in the browser.

How can I resolve this? If you can point me in the direction, I don't mind getting my hands dirty.

**Comment by sir-dunxalot** [comment]
Hi Dallas, my pleasure! I'm not sure why this might be happening. All this addon is doing is concatenating already compiled Javascript. Can you please confirm that it's this addon that's messing things up and not something else?

**Comment by dallasread** [comment]
If I remove ember-cli-concat, everything does function as expected.

**Comment by dallasread** [comment]
Looking more into it, I'm thinking it has to do with HTMLBars. Thanks!

**Comment by sir-dunxalot** [comment]
Ok, no worries! Let me know if you still can't figure it out and we can reopen this issue and double check everything in the concat is working correctly.
