### ISSUE TITLE
[Question]: how to exclude a file in my broccoli builds?

### ISSUE THREAD

**Issue by toranb** [sir-dunxalot/ember-cli-concat#19]
Assuming you still use this/ maintain this :) I'm curious how your upgrades have gone with ember-cli. I noticed that after the 1.13.13 upgrade this addon pulls in a test-loader file (that is already included in test-support right now). Would it be possible w/ options today to "exclude" something like ...

```
node_modules/ember-cli-mocha/vendor/test-loader.js
```

**Comment by toranb** [comment]
Looks like this did the trick

https://github.com/toranb/ember-cli-concat/commit/227b9d47e929ceced6f7c64c4be7f0f50a5b851e

**Comment by sir-dunxalot** [comment]
Ok, good to hear. Let me know if it turns out that didn't work. I haven't done any work with this after 1.12 but am open to maintaining it if there's interest.
