### ISSUE TITLE
broccoli-serviceworker compatibility

### ISSUE THREAD

**Issue by The-Don-Himself** [sir-dunxalot/ember-cli-concat#27]
Broccoli-serviceworker is a ServiceWorker generator for Broccoli and Ember.js. Derived from broccoli-manifest.

It's currently causing issues when used with ember-cli-concat where the files referenced by the service-worker are still the vendor.js and app.js.

It there any way to make them work together?

An ugly hack it to manually edit the generated service worker every time you build and deploy.

Cross-posting the issues for reference.
https://github.com/jkleinsc/broccoli-serviceworker/issues/46

**Comment by The-Don-Himself** [comment]
Found https://github.com/DockYard/ember-service-worker to be fully compatible.

**Comment by sir-dunxalot** [comment]
Great, thanks for the update!
